### ISSUE TITLE
本地 DataServer 如何连接？

### ISSUE THREAD

**Issue by gaizoule** [quantOS-org/DataCore#2]
我在本地部署了 DataServer， 但用 api.login 的时候用户名密码如何填写呢？

**Comment by gaizoule** [comment]
随便填写即可，只要不是空的。

那么如何配置用户名和密码呢？

**Comment by zpsymbol** [comment]
目前开源版本没有加入用户认证功能，但是认证接口有，用户可根据自己需求在该接口开发认证功能。
dataserver/server/src/main/scala/org/quantos/jads/gateway/SessionActor.scala文件里实现
checkUser(username: String, password: String) : Boolean 函数。
