### ISSUE TITLE
MapTables.cpp 编译错误

### ISSUE THREAD

**Issue by gaizoule** [quantOS-org/DataCore#3]
/home/hjs/Dropbox/py_ws/quantos/DataCore/mdlink/src/mdlink/public/MapTables.cpp:131:72: error: ‘transform’ was not declared in this scope
             transform(code.begin(), code.end(), code.begin(), ::toupper);

需要添加：
#include \<algorithm\> 到 MapTables.cpp 或者 MapTables.h 中.

**Comment by PKUJohnson** [comment]
已修正。
